In [1]:
import numpy as np;

In [9]:
arr_1d = np.array([1, 1, 2, 4 , 6]);
print(arr_1d);

[1 1 2 4 6]


In [10]:
type(arr_1d)

numpy.ndarray

In [15]:
arr_1d.ndim

1

In [29]:
arr_2d = np.array([[1, 3, 1], [2, 32 ,1]]);
print(arr_2d);

[[ 1  3  1]
 [ 2 32  1]]


In [18]:
type(arr_2d)

numpy.ndarray

In [19]:
arr_2d.ndim

2

In [23]:
arr_1d.size

5

In [24]:
arr_2d.size

6

In [25]:
arr_1d.size
arr_2d.size

6

In [26]:
arr_2d.dtype

dtype('int32')

In [27]:
arr_2d.shape

(2, 3)