In [1]:
import numpy as np;

In [9]:
mx_1 = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_1)
mx_1 = np.ones(4)
print(mx_1)
mx_1 = np.ones((3,3), dtype=int)
print(mx_1)
mx_1 = np.ones((3,3), dtype=str)
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [6]:
mx_0 = np.zeros((4,5))
print(mx_0)
mx_0 = np.zeros((4,5), dtype = bool)
print(mx_0)
mx_0 = np.zeros((4,5), dtype = str)
print(mx_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [10]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 3.93276254e-321]
 [9.82161409e+242 1.95066178e-153 8.41880588e+252]]
