In [1]:
import numpy as np
import random

In [12]:
np.random.random(3)

array([0.96826158, 0.31342418, 0.69232262])

In [3]:
np.random.random((3,3))

array([[0.8861702 , 0.09182463, 0.96737023],
       [0.79256917, 0.96822356, 0.44256084],
       [0.11963973, 0.85327043, 0.68799727]])

In [4]:
np.random.randint(1,100)

44

In [5]:
np.random.randint(1, 10, (3,3))

array([[2, 9, 1],
       [4, 1, 8],
       [6, 5, 5]])

In [7]:
np.random.randint(1, 5, (4, 2, 2))

array([[[4, 2],
        [3, 4]],

       [[2, 3],
        [4, 2]],

       [[2, 2],
        [3, 3]],

       [[2, 1],
        [4, 2]]])

In [8]:
np.random.seed(1)
np.random.randint(1, 10, (2, 3, 3))

array([[[6, 9, 6],
        [1, 1, 2],
        [8, 7, 3]],

       [[5, 6, 3],
        [5, 3, 5],
        [8, 8, 2]]])

In [10]:
np.random.seed(1)
np.random.randint(1, 10, (2, 3, 3))

array([[[6, 9, 6],
        [1, 1, 2],
        [8, 7, 3]],

       [[5, 6, 3],
        [5, 3, 5],
        [8, 8, 2]]])

In [11]:
np.random.rand(3)

array([0.14038694, 0.19810149, 0.80074457])

In [13]:
np.random.rand(4, 4)

array([[0.87638915, 0.89460666, 0.08504421, 0.03905478],
       [0.16983042, 0.8781425 , 0.09834683, 0.42110763],
       [0.95788953, 0.53316528, 0.69187711, 0.31551563],
       [0.68650093, 0.83462567, 0.01828828, 0.75014431]])

In [15]:
x = [1, 2, 5, 10]
np.random.choice(x)

10

In [16]:
np.random.choice(x)

1

In [17]:
for i in range(5):
    print(np.random.choice(x))

1
2
10
5
10


In [18]:
x

[1, 2, 5, 10]

In [19]:
np.random.permutation(x)

array([ 1,  2,  5, 10])

In [20]:
np.random.permutation(x)

array([10,  2,  5,  1])

In [ ]:
#https://docs.python.org/3/library/random.html