In [1]:
import numpy as np;

In [2]:
#np.arange(start, end, steps)
ar_1d = np.arange(1,13)
print(ar_1d)
ar = np.arange(2, 11, 2)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10]


In [3]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [4]:
ar_2d = ar_1d.reshape((4,3))
print(ar_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
ar_3d = ar_1d.reshape(3,2,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [6]:
ar = np.arange(1,11).reshape(5,2)
print(ar)
ar.ravel()


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
ar.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [9]:
ar.T

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])